"use client";
import { NextPage } from "next";
import Header from "../Components/Header";
import Head from "next/head";
import Link from "next/link";
import { Button, Container } from "reactstrap";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next Store Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <main>
        <Container className="py-5 text-center">
          <h1 className="mt-5 display-1">
            O melhor jeito de comprar o que você ama
          </h1>
          <p className="my-4">
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Praesentium, laboriosam.
          </p>
          <Link href="/Products/">
            <Button color="dark" className="px-4 pb-2">
              Conheça nossos produtos
            </Button>
          </Link>
        </Container>
      </main>
    </>
  );
};

export default Home;
